name: release

on:
  push:
    branches:
      - main
  workflow_run:
    workflows:
      - test
    types:
      - completed

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          release-type: go
